name: Playwright Tests

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main, feature ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    environment: test_tst04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Ensure browsers installed
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run testng tests
        run: mvn test

      - name: Environment variable
        run: echo "ENV_TST04=${{ vars.ENV_TST04 }}"

      - name: Secret - Password
        run: echo '${{ secrets.ENV_PASS }}'
